# Generated by Django 2.2.2 on 2019-07-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='body',
            field=models.TextField(verbose_name='Notes Body'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Notes Title'),
        ),
    ]
